namespace EnterpriseLink.Shared.Domain.Entities;

/// <summary>
/// Immutable record of a before/after state change on any <c>AuditableEntity</c>
/// within the system, written atomically in the same database transaction as the
/// change itself.
///
/// <para><b>Design: intentionally does NOT extend <c>AuditableEntity</c></b>
/// Audit logs are append-only. They must never be updated, soft-deleted, or
/// audited themselves. Extending <c>AuditableEntity</c> would add <c>IsDeleted</c>
/// and <c>UpdatedAt</c> (semantically wrong for an immutable record) and would
/// cause the audit interceptor to recursively audit its own writes.
/// </para>
///
/// <para><b>Acceptance criterion: Before/after state stored</b>
/// <c>OldValues</c> holds the serialised property values <em>before</em> the change;
/// <c>NewValues</c> holds the values <em>after</em>. Both are JSON dictionaries
/// (property-name → string). <c>OldValues</c> is <c>null</c> for inserts;
/// <c>NewValues</c> is <c>null</c> for hard deletes (which never happen in normal
/// application flow — soft deletes appear as <c>Action = "Modified"</c> with
/// <c>IsDeleted</c> flipping from <c>false</c> to <c>true</c> in <c>NewValues</c>).
/// </para>
///
/// <para><b>Indexing strategy</b>
/// The table is indexed on (<c>EntityType</c>, <c>EntityId</c>) for point lookups
/// ("show me all changes to Transaction X"), on <c>TenantId</c> for tenant-scoped
/// compliance reports, and on <c>OccurredAt</c> for time-range queries
/// ("what changed in the last 24 hours?").
/// </para>
/// </summary>
public sealed class AuditLog
{
    /// <summary>Primary key — generated by the database via NEWSEQUENTIALID().</summary>
    public Guid AuditLogId { get; set; }

    /// <summary>
    /// Short name of the entity type that changed (e.g. <c>"Transaction"</c>,
    /// <c>"Tenant"</c>). Used as a partition key for compliance queries.
    /// </summary>
    public string EntityType { get; set; } = string.Empty;

    /// <summary>
    /// Primary-key value(s) of the changed entity serialised as a string.
    /// For composite keys the values are comma-separated.
    /// </summary>
    public string EntityId { get; set; } = string.Empty;

    /// <summary>
    /// Owning tenant at the time of the change. <c>null</c> for entities that are
    /// not tenant-scoped (e.g. <c>Tenant</c> itself).
    /// </summary>
    public Guid? TenantId { get; set; }

    /// <summary>
    /// The EF Core change-tracker action: <c>"Added"</c>, <c>"Modified"</c>,
    /// or <c>"Deleted"</c>. Soft deletes appear as <c>"Modified"</c> with
    /// <c>IsDeleted</c> set to <c>true</c> in <c>NewValues</c>.
    /// </summary>
    public string Action { get; set; } = string.Empty;

    /// <summary>
    /// JSON dictionary of property values <em>before</em> the change.
    /// <c>null</c> for <c>Added</c> entries (no previous state exists).
    /// </summary>
    public string? OldValues { get; set; }

    /// <summary>
    /// JSON dictionary of property values <em>after</em> the change.
    /// <c>null</c> for hard-delete entries (which do not occur in normal flow).
    /// </summary>
    public string? NewValues { get; set; }

    /// <summary>UTC timestamp when the change was committed to the database.</summary>
    public DateTimeOffset OccurredAt { get; set; }
}
