using EnterpriseLink.Shared.Domain.MultiTenancy;

namespace EnterpriseLink.Shared.Domain.Entities;

/// <summary>
/// Persists every CSV row that failed schema validation, business-rule checks, or
/// duplicate detection, so that operators can review, correct, and re-submit invalid
/// source data without touching the main <see cref="Transaction"/> table.
///
/// <para><b>Tenant isolation</b>
/// Implements <see cref="ITenantScoped"/>. <c>TenantId</c> is auto-injected by
/// <c>AppDbContext.ApplyTenantId</c> on insert; the global EF query filter
/// restricts reads to the current tenant. No service code sets <c>TenantId</c>
/// manually.
/// </para>
///
/// <para><b>Raw data fidelity</b>
/// <c>RawData</c> stores the entire field dictionary from <c>ParsedRow.Fields</c>
/// serialised as JSON. This preserves the exact bytes from the source CSV so that
/// operators can diagnose exactly what was in the file without re-downloading it.
/// </para>
///
/// <para><b>Error detail</b>
/// <c>ValidationErrors</c> stores a JSON array of formatted error strings
/// (e.g. <c>["[RequiredFieldMissing] Amount: No amount field found"]</c>).
/// <c>FailureReason</c> stores the stage that first rejected the row
/// (<c>"Schema"</c>, <c>"BusinessRule"</c>, or <c>"Duplicate"</c>).
/// </para>
/// </summary>
public sealed class InvalidTransaction : AuditableEntity, ITenantScoped
{
    /// <summary>Primary key. Generated by the database via NEWSEQUENTIALID().</summary>
    public Guid InvalidTransactionId { get; set; }

    /// <summary>
    /// The <c>FileUploadedEvent.UploadId</c> that produced this invalid row.
    /// Indexed so that all errors for a single upload can be retrieved efficiently.
    /// </summary>
    public Guid UploadId { get; set; }

    /// <summary>
    /// The tenant that owns this invalid record.
    /// Auto-set by <c>AppDbContext.ApplyTenantId</c>; never set manually.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>1-based row number within the source CSV file (from <c>ParsedRow.RowNumber</c>).</summary>
    public int RowNumber { get; set; }

    /// <summary>
    /// JSON-serialised dictionary of all column values from the source CSV row
    /// (<c>ParsedRow.Fields</c>). Stored verbatim so the exact input is auditable.
    /// </summary>
    public string RawData { get; set; } = string.Empty;

    /// <summary>
    /// JSON array of formatted validation error strings, one entry per error.
    /// Format: <c>"[ErrorCode] FieldName: Message"</c>.
    /// </summary>
    public string ValidationErrors { get; set; } = string.Empty;

    /// <summary>
    /// The pipeline stage that first rejected the row: <c>Schema</c>,
    /// <c>BusinessRule</c>, or <c>Duplicate</c>.
    /// </summary>
    public string FailureReason { get; set; } = string.Empty;

    // ── Navigation ────────────────────────────────────────────────────────────

    /// <summary>Navigation property to the owning tenant. Loaded on demand.</summary>
    public Tenant? Tenant { get; set; }
}
