using EnterpriseLink.Shared.Domain.Enums;

namespace EnterpriseLink.Shared.Domain.Entities;

/// <summary>
/// Represents an enterprise customer (tenant) on the platform.
/// This is the root aggregate for the multi-tenant boundary.
/// Every piece of data on the platform is owned by exactly one Tenant.
/// </summary>
public class Tenant : AuditableEntity
{
    /// <summary>Primary key — GUID generated by NEWSEQUENTIALID() for clustered index efficiency.</summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// Legal or trading name of the organisation.
    /// Unique across all tenants — enforced via unique index.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Industry vertical used to apply compliance rules (HIPAA, PCI, etc.).
    /// Stored as string in the database for readability and forward-compatibility.
    /// </summary>
    public IndustryType IndustryType { get; set; }

    /// <summary>
    /// Controls whether the tenant can log in and use the platform.
    /// Inactive tenants cannot authenticate — no data is deleted.
    /// </summary>
    public bool IsActive { get; set; } = true;

    // ── Navigation properties ─────────────────────────────────────────────────

    /// <summary>All users that belong to this tenant.</summary>
    public ICollection<User> Users { get; set; } = new List<User>();

    /// <summary>All transactions submitted by this tenant.</summary>
    public ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}
