using EnterpriseLink.Shared.Domain.Enums;
using EnterpriseLink.Shared.Domain.MultiTenancy;

namespace EnterpriseLink.Shared.Domain.Entities;

/// <summary>
/// Represents a single financial transaction submitted by a tenant for reconciliation.
/// This is the highest-volume table in the system — indexing strategy is critical.
/// Design target: 10M+ transactions per day across all tenants.
/// </summary>
public class Transaction : AuditableEntity, ITenantScoped
{
    /// <summary>Primary key — GUID generated by NEWSEQUENTIALID() for sequential insert performance.</summary>
    public Guid TransactionId { get; set; }

    /// <summary>
    /// Owning tenant. All queries are automatically filtered by this value
    /// via the EF Core global query filter — no service-layer filtering required.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// Optional: the user who submitted this transaction.
    /// Null for system/API-submitted transactions.
    /// </summary>
    public Guid? UserId { get; set; }

    /// <summary>
    /// Monetary value of the transaction.
    /// Stored as decimal(18,4) to support high-precision financial calculations.
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>Current state in the reconciliation pipeline.</summary>
    public TransactionStatus Status { get; set; } = TransactionStatus.Pending;

    /// <summary>
    /// Reference ID from the upstream/legacy system (bank core, EHR, etc.).
    /// Used for deduplication and reconciliation matching.
    /// Not required — some transactions are generated internally.
    /// </summary>
    public string? ExternalReferenceId { get; set; }

    /// <summary>
    /// Human-readable description or memo for this transaction.
    /// Useful for audit trail and manual review workflows.
    /// </summary>
    public string? Description { get; set; }

    // ── Data lineage (Story 3) ────────────────────────────────────────────────

    /// <summary>
    /// The <c>FileUploadedEvent.UploadId</c> that produced this transaction.
    /// Null for transactions created outside the CSV batch-import pipeline.
    /// Join to <c>ProcessedUploads</c> to trace the full source → transformation chain.
    /// </summary>
    public Guid? UploadId { get; set; }

    /// <summary>
    /// The source system that submitted the file (e.g. <c>"SalesForce"</c>, <c>"SAP"</c>).
    /// Null for transactions created outside the CSV batch-import pipeline.
    /// Together with <c>ExternalReferenceId</c> this provides a complete data-lineage
    /// fingerprint: where the data came from and what its identity was in the source.
    /// </summary>
    public string? SourceSystem { get; set; }

    // ── Navigation properties ─────────────────────────────────────────────────

    /// <summary>The tenant this transaction belongs to.</summary>
    public Tenant Tenant { get; set; } = null!;

    /// <summary>The user who submitted this transaction (if applicable).</summary>
    public User? User { get; set; }
}
