using EnterpriseLink.Shared.Domain.Enums;
using EnterpriseLink.Shared.Domain.MultiTenancy;

namespace EnterpriseLink.Shared.Domain.Entities;

/// <summary>
/// Represents a human user within a specific tenant.
/// Email uniqueness is enforced per-tenant (not globally) — the same email
/// can exist under different tenants without conflict.
/// </summary>
public class User : AuditableEntity, ITenantScoped
{
    /// <summary>Primary key — GUID generated by NEWSEQUENTIALID().</summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Tenant this user belongs to.
    /// Populated automatically by the DbContext on insert via ITenantScoped.
    /// Never trust client-supplied TenantId — always use ITenantContext.
    /// </summary>
    public Guid TenantId { get; set; }

    /// <summary>
    /// User's email address. Unique within a tenant.
    /// Composite unique index: (TenantId, Email).
    /// </summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>
    /// Bcrypt / Argon2 hash of the user's password.
    /// Plaintext passwords are NEVER stored.
    /// </summary>
    public string PasswordHash { get; set; } = string.Empty;

    /// <summary>Role determines what actions this user can perform.</summary>
    public UserRole Role { get; set; }

    /// <summary>
    /// Inactive users cannot authenticate.
    /// Use this instead of soft delete for user suspension.
    /// </summary>
    public bool IsActive { get; set; } = true;

    // ── Navigation properties ─────────────────────────────────────────────────

    /// <summary>The tenant this user belongs to.</summary>
    public Tenant Tenant { get; set; } = null!;

    /// <summary>Transactions submitted or owned by this user.</summary>
    public ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}
