namespace EnterpriseLink.Ingestion.Storage;

/// <summary>
/// Abstraction over the file storage backend used by the Ingestion service.
///
/// <para>
/// Implementations hide the details of <em>where</em> a file is written (local disk,
/// Azure Blob Storage, AWS S3, …) behind a single uniform operation. The controller
/// depends only on this interface, making the storage provider swappable without any
/// change to controller or validation logic.
/// </para>
///
/// <para><b>Tenant isolation</b></para>
/// Every write is automatically scoped under <c>{tenantId}/{uploadId}/</c>, ensuring
/// that files from different tenants are physically separated in the backing store.
/// No cross-tenant reads are possible via this interface because the caller must supply
/// an explicit, validated <c>tenantId</c>.
///
/// <para><b>Implementing a new provider</b></para>
/// <list type="number">
///   <item>Create a class that implements <see cref="IFileStorageService"/>.</item>
///   <item>Add a new <c>Provider</c> value to <c>FileStorageOptions</c>.</item>
///   <item>Register the new class in <c>StorageServiceExtensions.AddFileStorage</c>.</item>
/// </list>
///
/// <para><b>Current providers</b></para>
/// <list type="bullet">
///   <item><description><c>local</c> — <see cref="Local.LocalFileStorageService"/></description></item>
///   <item><description><c>azureblob</c> — planned (future story)</description></item>
/// </list>
/// </summary>
public interface IFileStorageService
{
    /// <summary>
    /// Writes the uploaded file to the backing store and returns a <see cref="StorageResult"/>
    /// describing where the file was stored.
    ///
    /// <para>
    /// Implementations must use streaming I/O — the file content must not be loaded
    /// entirely into memory. Use <see cref="IFormFile.OpenReadStream"/> and copy to the
    /// destination via <c>CopyToAsync</c>.
    /// </para>
    ///
    /// <para>
    /// The stored path follows the pattern <c>{tenantId}/{uploadId}/{fileName}</c>,
    /// giving natural tenant and upload isolation.
    /// </para>
    /// </summary>
    /// <param name="tenantId">
    /// The resolved internal tenant identifier. Used as the top-level directory/container
    /// prefix to enforce physical tenant isolation.
    /// </param>
    /// <param name="uploadId">
    /// The unique identifier for this upload session (generated by the controller).
    /// Used as the second-level prefix so each upload has its own isolated storage slot.
    /// </param>
    /// <param name="file">The validated <see cref="IFormFile"/> from the multipart request.</param>
    /// <param name="cancellationToken">Request cancellation token.</param>
    /// <returns>
    /// A <see cref="StorageResult"/> with the relative and full paths, the provider name,
    /// and the UTC timestamp of the write.
    /// </returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown if the backing store is unavailable or the write fails after all retries.
    /// </exception>
    Task<StorageResult> StoreAsync(
        Guid tenantId,
        Guid uploadId,
        IFormFile file,
        CancellationToken cancellationToken = default);
}
