using EnterpriseLink.Shared.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EnterpriseLink.Shared.Infrastructure.Persistence.Configurations;

/// <summary>
/// EF Core entity type configuration for <see cref="ProcessedUpload"/>.
///
/// <para>
/// Key design choices:
/// </para>
/// <list type="bullet">
///   <item>
///     <description>
///       <c>UploadId</c> is the primary key with <c>ValueGeneratedNever</c> — the value
///       is supplied by the caller (from <c>FileUploadedEvent.UploadId</c>), not the
///       database. The PK uniqueness constraint is the distributed lock that prevents
///       concurrent double-processing.
///     </description>
///   </item>
///   <item>
///     <description>
///       <see cref="ProcessedUpload"/> is intentionally NOT <c>ITenantScoped</c>.
///       The idempotency guard must locate a row by <c>UploadId</c> regardless of the
///       current tenant context, so no tenant-partition filter is configured here.
///       Only the soft-delete filter (<c>IsDeleted = false</c>) is applied; the guard
///       bypasses even that via <c>IgnoreQueryFilters()</c> to detect soft-deleted records.
///     </description>
///   </item>
/// </list>
/// </summary>
internal sealed class ProcessedUploadConfiguration : IEntityTypeConfiguration<ProcessedUpload>
{
    /// <inheritdoc />
    public void Configure(EntityTypeBuilder<ProcessedUpload> builder)
    {
        // ── Primary key ────────────────────────────────────────────────────────
        // UploadId comes from the event — never generated by the database.
        // The PK uniqueness constraint is the idempotency mechanism.
        builder.HasKey(p => p.UploadId);
        builder.Property(p => p.UploadId).ValueGeneratedNever();

        // ── Properties ────────────────────────────────────────────────────────
        builder.Property(p => p.Status)
            .HasConversion<string>()
            .HasMaxLength(50)
            .IsRequired();

        builder.Property(p => p.SourceSystem)
            .HasMaxLength(200)
            .IsRequired();

        // RowsInserted has a sensible default of 0 (set by CLR, not DB default).
        builder.Property(p => p.RowsInserted).IsRequired();

        // ── Indexes ────────────────────────────────────────────────────────────
        // TenantId — used by audit queries ("show all uploads for tenant X").
        builder.HasIndex(p => p.TenantId)
            .HasDatabaseName("IX_ProcessedUploads_TenantId");

        // (TenantId, CreatedAt) — supports time-windowed audit range scans.
        builder.HasIndex(p => new { p.TenantId, p.CreatedAt })
            .HasDatabaseName("IX_ProcessedUploads_TenantId_CreatedAt");

        // ── Relationships ──────────────────────────────────────────────────────
        // FK to Tenants; no cascade delete — the record is kept for audit.
        builder.HasOne(p => p.Tenant)
            .WithMany()
            .HasForeignKey(p => p.TenantId)
            .OnDelete(DeleteBehavior.Restrict);

        // ── Temporal history (Story 1) ─────────────────────────────────────────
        builder.ToTable("ProcessedUploads", t => t.IsTemporal(tb =>
        {
            tb.UseHistoryTable("ProcessedUploadsHistory");
            tb.HasPeriodStart("SysStartTime").HasColumnName("SysStartTime");
            tb.HasPeriodEnd("SysEndTime").HasColumnName("SysEndTime");
        }));

        // ── Soft-delete filter ─────────────────────────────────────────────────
        // This filter is intentionally bypassed by the idempotency guard via
        // IgnoreQueryFilters() so that soft-deleted records are detected too
        // (preventing reprocessing of "deleted" upload tracking records).
        builder.HasQueryFilter(p => !p.IsDeleted);
    }
}
